Task 3.1.2
hehnev-and-company/Task-7 pull request #1
Opened 2023-05-31 13:53 UTC by kriian

2023-05-31 15:00 UTC, pdasilem requested changes

2023-05-31 15:00 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
избавиться от eager

2023-05-31 15:00 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserDetailsServiceImpl.java
> +    public void setUserRepository(UserRepository userRepository) {
почему внедрение через сеттер?

2023-05-31 15:00 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +        this.userRepository = userRepository;
почему через сеттер?

2023-05-31 15:00 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    @Transactional
где еще необходимо поставить эту аннотацию?

2023-05-31 15:30 UTC, kriian commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserDetailsServiceImpl.java
> +    public void setUserRepository(UserRepository userRepository) {
Внедрения через сеттер считается лучшей практикой в Spring, так как это соответствует принципу инкапсуляции, при котором состояние объекта не непосредственно передается внешним классам. Так же мы можно в методе реализовать доп логику перед внедрением.

2023-05-31 15:37 UTC, kriian commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    @Transactional
В сервисном слое аннотация @Transactional должна быть применена к методам, которые изменяют данные в базе данных. Например, методы, которые добавляют, обновляют или удаляют записи.

2023-05-31 18:20 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserDetailsServiceImpl.java
> +    public void setUserRepository(UserRepository userRepository) {
В твоем случае является ли зависимость обязательной? Будешь ли ты ее менять (или ее свойства) во время исполнения? Исходя из этого ты принимаешь решение по внедрению через сеттер или конструктор. мое мнение - в данном конкретном примере нужно внедрять через конструктор. Плюсы такого варианта перевешивают минусы.

2023-05-31 18:24 UTC, pdasilem requested changes

2023-05-31 18:24 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/AdminController.java
> +        this.userService = userService;
через конструктор предпочтительнее внедрять

2023-05-31 18:24 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/AdminController.java
> +        this.userService = userService;
и так везде

2023-05-31 18:24 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +@Transactional
1. либо добавь нужный параметр и поставь над теми методами, где этот параметр должен быть значением по-умолчанию
2. либо просто поставь над теми методами, где она необходима

2023-06-01 11:27 UTC, pdasilem approved these changes
отлично

2023-06-01 11:40 UTC, merged